apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: component-97e48bhbgxh5j
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: component-97e48bhbgxh5j
    app.kubernetes.io/part-of: test-gitlabrenovate-1wox8ocbnvphb
  name: component-97e48bhbgxh5j
spec:
  ports:
  - name: http-8081
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: go-app
    app.kubernetes.io/instance: component-97e48bhbgxh5j
status:
  loadBalancer: {}
